apiVersion: v1
kind: Template
labels:
  template: f8a-stacks-report
metadata:
  name: f8a-stacks-report
  annotations:
    description: f8a-stacks-report
objects:
- apiVersion:  batch/v1beta1
  kind: CronJob
  metadata:
    name: f8a-stacks-report
    annotations:
      description: f8a-stacks-report
  spec:
    successfulJobsHistoryLimit: 4
    failedJobsHistoryLimit: 1
    concurrencyPolicy: "Forbid"
    schedule: "${CRON_SCHEDULE}"
    jobTemplate:
      spec:
        template:
          spec:
            restartPolicy: Never
            containers:
            - name: f8a-stacks-report
              image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
              imagePullPolicy: Always
              env:
                - name: BAYESIAN_GREMLIN_HTTP_SERVICE_HOST
                  value: bayesian-gremlin-http
                - name: BAYESIAN_GREMLIN_HTTP_SERVICE_PORT
                  value: "8182"
                - name: GITHUB_CVE_REPO
                  value: ${GITHUB_CVE_REPO}
                - name: KEEP_DB_META_NUM_DAYS
                  value: ${KEEP_DB_META_NUM_DAYS}
                - name: AWS_S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws
                      key: s3-secret-access-key
                - name: AWS_S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws
                      key: s3-access-key-id
                - name: AWS_S3_SECRET_ACCESS_KEY_REPORT_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: developer-analytics-audit-report-s3
                      key: aws_secret_access_key
                - name: AWS_S3_ACCESS_KEY_ID_REPORT_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: developer-analytics-audit-report-s3
                      key: aws_access_key_id
                - name: AWS_S3_SECRET_ACCESS_KEY_NPM_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: cvae-npm-insights-s3
                      key: aws_secret_access_key
                - name: AWS_S3_ACCESS_KEY_ID_NPM_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: cvae-npm-insights-s3
                      key: aws_access_key_id
                - name: AWS_S3_SECRET_ACCESS_KEY_MVN_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: hpf-maven-insights-s3
                      key: aws_secret_access_key
                - name: AWS_S3_ACCESS_KEY_ID_MVN_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: hpf-maven-insights-s3
                      key: aws_access_key_id
                - name: AWS_S3_SECRET_ACCESS_KEY_PYPI_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: hpf-pypi-insights-s3
                      key: aws_secret_access_key
                - name: AWS_S3_ACCESS_KEY_ID_PYPI_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: hpf-pypi-insights-s3
                      key: aws_access_key_id
                - name: AWS_S3_SECRET_ACCESS_KEY_GOLANG_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: golang-insights-s3
                      key: aws_secret_access_key
                - name: AWS_S3_ACCESS_KEY_ID_GOLANG_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: golang-insights-s3
                      key: aws_access_key_id
                - name: DEPLOYMENT_PREFIX
                  valueFrom:
                    configMapKeyRef:
                      name: bayesian-config
                      key: deployment-prefix
                - name: AWS_S3_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: bayesian-config
                      key: aws-default-region
                - name: PGBOUNCER_SERVICE_HOST
                  value: bayesian-pgbouncer
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database
                      name: coreapi-postgres
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: coreapi-postgres
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: coreapi-postgres
                - name: SENTRY_AUTH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: worker
                      key: sentry-auth-token
                - name: REPORT_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: developer-analytics-audit-report-s3
                      key: bucket
                - name: NPM_MODEL_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: cvae-npm-insights-s3
                      key: bucket
                - name: MAVEN_MODEL_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: hpf-maven-insights-s3
                      key: bucket
                - name: PYPI_MODEL_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: hpf-pypi-insights-s3
                      key: bucket
                - name: GOLANG_MODEL_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: golang-insights-s3
                      key: bucket
                - name: GOLANG_TRAINING_REPO
                  value: ${GOLANG_TRAINING_REPO}
                - name: MAVEN_TRAINING_REPO
                  value: ${MAVEN_TRAINING_REPO}
                - name: NPM_TRAINING_REPO
                  value: ${NPM_TRAINING_REPO}
                - name: PYPI_TRAINING_REPO
                  value: ${PYPI_TRAINING_REPO}
                - name: GREMLIN_QUERY_SIZE
                  value: "25"
              resources:
                requests:
                  memory: ${MEMORY_REQUEST}
                  cpu: ${CPU_REQUEST}
                limits:
                  memory: ${MEMORY_LIMIT}
                  cpu: ${CPU_LIMIT}
parameters:
- description: Docker registry
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "quay.io"

- description: Docker image
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "openshiftio/fabric8-analytics-f8a-stacks-report"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Schedule
  displayName: Schedule
  required: true
  name: CRON_SCHEDULE
  value: "0 0 * * *"

- description: CPU request
  displayName: CPU request
  required: true
  name: CPU_REQUEST
  value: "250m"

- description: CPU limit
  displayName: CPU limit
  required: true
  name: CPU_LIMIT
  value: "500m"

- description: Memory request
  displayName: Memory request
  required: true
  name: MEMORY_REQUEST
  value: "1024Mi"

- description: Memory limit 
  displayName: Memory limit
  required: true
  name: MEMORY_LIMIT
  value: "2048Mi"

- description: Keep only last n days of meta data from celery task table
  displayName: Keep last n days of meta data
  required: true
  name: KEEP_DB_META_NUM_DAYS
  value: "7"

- description: "Golang Training Repo to fetch training file"
  displayName: Golang Training Repo
  required: true
  name: GOLANG_TRAINING_REPO
  value: "https://github.com/fabric8-analytics/f8a-golang-insights"

- description: "NPM Training Repo to fetch training file"
  displayName: NPM Training Repo
  required: true
  name: NPM_TRAINING_REPO
  value: "https://github.com/fabric8-analytics/fabric8-analytics-npm-insights"

- description: "Python Training Repo to fetch training file"
  displayName: Python Training Repo
  required: true
  name: PYPI_TRAINING_REPO
  value: "https://github.com/fabric8-analytics/f8a-pypi-insights"

- description: "Maven Training Repo to fetch training file"
  displayName: Maven Training Repo
  required: true
  name: MAVEN_TRAINING_REPO
  value: "https://github.com/fabric8-analytics/f8a-hpf-insights"

- description: "Github Repo to fetch CVE PRs from"
  displayName: Github CVE Repo
  required: true
  name: GITHUB_CVE_REPO
  value: "fabric8-analytics"
